// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG1lyNqjnYd2VRFrvZ4-YzamyXrhK7k3o',
    appId: '1:293689309038:web:230b4f35f4c0e5a4fef37f',
    messagingSenderId: '293689309038',
    projectId: 'musicboxd-e0c37',
    authDomain: 'musicboxd-e0c37.firebaseapp.com',
    storageBucket: 'musicboxd-e0c37.firebasestorage.app',
    measurementId: 'G-T1MZFVVLSM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAWoyBncfLD5ILAXcykzNno7O1WLf1w1s',
    appId: '1:293689309038:ios:7932001c5bdaed24fef37f',
    messagingSenderId: '293689309038',
    projectId: 'musicboxd-e0c37',
    storageBucket: 'musicboxd-e0c37.firebasestorage.app',
    iosBundleId: 'com.example.musicboxdFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAWoyBncfLD5ILAXcykzNno7O1WLf1w1s',
    appId: '1:293689309038:ios:7932001c5bdaed24fef37f',
    messagingSenderId: '293689309038',
    projectId: 'musicboxd-e0c37',
    storageBucket: 'musicboxd-e0c37.firebasestorage.app',
    iosBundleId: 'com.example.musicboxdFlutter',
  );

}